'''Input: TCTAGTCTAGTCTAGTCTATTTAGATCTCTTTTTTTCTTTTTTTCTTTTTTTCTTTTTAGATCTTCTTTTTTTTCTTTTTTTGGCCCCGGACATACCTGCTGTCAGAGATCAGATCAGATCAGATCAGATCTTGAATACCTATGCGAGTCTGAAACACGAATAGTTCAGGCGTGCAAAGACAAGATCAGATCAGATCAGATCAGATCAGATCAGATCAGATCCGCTAAGCACACGCCGCA
pattern: AGATC
Output: 5'''





input_str = "TCTAGTCTAGTCTAGTCTATTTAGATCTCTTTTTTTCTTTTTTTCTTTTTTTCTTTTTAGATCTTCTTTTTTTTCTTTTTTTGGCCCCGGACATACCTGCTGTCAGA" \
            "GATCAGATCAGATCAGATCAGATCTTGAATACCTATGCGAGTCTGAAACACGAATAGTTCAGGCGTGCAAAGACAAGATCAGATCAGATCAGATCAGATCAGATCAGATCAGATCCGCTAAGCACACGCCGCA"

sub_str = "AGATC"


start = 0
count = 0


# input_str = "abcdefghijdefdsfsddefdfd"
# sub_str = "def"


# s = input_str.find(sub_str, 0)
# print(s)
while start < len(input_str):

    pos = input_str.find(sub_str, start)

    if pos != -1:
        start = pos + 1
        count += 1
    else:
        break
    # print("n")

print(count)


# def find_substring_count(istr):












